//! The `*` and `+` mixers and the per-node kernel dispatch.

use crate::dsp::effects::{self};

use super::{
    additive, analog_pair, analog_percussion, bass_voice, braids_cloud, braids_digital,
    braids_filter, braids_five, braids_fm, braids_formant, braids_noise, braids_percussion,
    braids_physical, braids_struck, braids_subsync, braids_triple, braids_wave_bank,
    braids_wave_line, chip_pair, chord_pair, clock_noise_pair, digital_drum, dual_kick,
    elements_internal, env, feedback_metal, filter, fm, fm_drum, fm_pair, frame_lfo, fusion_drum,
    grain_pair, hat_pair, modal_pair, musicdsp_synth, number_station, osc, particle_pair,
    peak_function, peak_pulse, phase_pair, rings_part, sample, shape_pair, six_op_original,
    snare_pair, spectrum_pair, speech_original, stage_chain, stage_segment, string_choir,
    string_machine_pair, string_pair, swarm_pair, table_terrain_pair, terrain_pair, tidal_function,
    tidal_poly, va_filter, vactrol_gate, wavetable,
};
use super::{Inp, Kx, Node, NodeSpec, NodeState, MAX_PORTS};

/// Renders one non-effect node for a block (`out.len()` frames).
pub fn run(
    spec: &NodeSpec,
    ins: &[Inp<'_>; MAX_PORTS],
    st: &mut NodeState,
    mem: &mut [f32],
    out: &mut [f32],
    kx: &mut Kx<'_>,
) {
    match spec.node {
        Node::DsfOsc => musicdsp_synth::dsf(ins, st, out, kx),
        Node::ChebyshevOsc => musicdsp_synth::chebyshev(ins, st, out, kx),
        Node::GaussianNoise => musicdsp_synth::gaussian(ins, st, out, kx),
        Node::LorenzOsc => musicdsp_synth::lorenz(ins, st, out, kx),
        Node::RosslerOsc => musicdsp_synth::rossler(ins, st, out, kx),
        Node::AmFormantOsc => musicdsp_synth::am_formant(ins, st, mem, out, kx),
        Node::SinOsc => osc::sine(ins, st, out, kx),
        Node::Saw => osc::saw(ins, st, out, kx),
        Node::Pulse => osc::pulse(ins, st, out, kx),
        Node::Tri => osc::tri(ins, st, out, kx),
        Node::SubOsc => osc::sub(ins, st, out, kx),
        Node::WhiteNoise => osc::noise(st, out, kx),
        Node::HostInputL | Node::HostInputR => out.fill(0.0),
        Node::Vco { unison_max } => osc::vco(unison_max, ins, st, mem, out, kx),
        Node::Lpf => filter::biquad(effects::prim::Shape::Lowpass, ins, st, out, kx),
        Node::Hpf => filter::biquad(effects::prim::Shape::Highpass, ins, st, out, kx),
        Node::Bpf => filter::biquad(effects::prim::Shape::Bandpass, ins, st, out, kx),
        Node::Ladder => filter::ladder(ins, st, out, kx),
        Node::Svf => filter::svf(ins, st, out, kx),
        Node::Delay => filter::delay(ins, st, mem, out, kx),
        Node::Comb => filter::comb(ins, st, mem, out, kx),
        Node::EnvPerc => env::perc(ins, st, out, kx),
        Node::EnvAdsr => env::adsr(ins, st, out, kx),
        Node::Line => env::line(ins, st, out, kx),
        Node::SamplePlay(bank) => sample::play(bank, ins, st, out, kx),
        Node::Mul => {
            for (i, y) in out.iter_mut().enumerate() {
                *y = ins[0].at(i) * ins[1].at(i);
            }
        }
        Node::Add => {
            for (i, y) in out.iter_mut().enumerate() {
                *y = ins[0].at(i) + ins[1].at(i);
            }
        }
        Node::Const(v) => out.fill(v),
        Node::AuxOut | Node::Out3 | Node::Out4 => out.fill(0.0),
        Node::Param(_) => out.fill(ins[0].first()),
        Node::FmOp => fm::op(ins, st, out, kx),
        Node::FmMod => fm::modulate(ins, out),
        Node::FmDrum => fm_drum::render(ins, st, out, kx),
        Node::FeedbackMetal => feedback_metal::render(ins, st, out, kx),
        Node::DigitalDrumCore => digital_drum::render_drum(ins, st, mem, out, kx),
        Node::DigitalSnareCore => digital_drum::render_snare(ins, st, mem, out, kx),
        Node::DigitalMetalCore => digital_drum::metal::render_metal(ins, st, mem, out, kx),
        Node::DigitalHatCore => digital_drum::metal::render_hat(ins, st, mem, out, kx),
        Node::BassCore => bass_voice::render(ins, st, mem, out, kx),
        Node::AnalogPercussion => analog_percussion::render(ins, st, out, kx),
        Node::VaSource => va_filter::source(ins, st, out, kx),
        Node::VaFilter => va_filter::filter(ins, st, out, kx),
        Node::PhasePair => phase_pair::render(ins, st, out, kx),
        Node::FmPair => fm_pair::render(ins, st, out, kx),
        Node::SixOpOriginal => six_op_original::render(ins, st, mem, out, kx),
        Node::SpeechOriginal => speech_original::render(ins, st, mem, out, kx),
        Node::RingsPart => rings_part::render(ins, st, mem, out, kx),
        Node::StringChoir => string_choir::render(ins, st, mem, out, kx),
        Node::ElementsInternal => elements_internal::render(ins, st, mem, out, kx),
        Node::TidalFunction => tidal_function::render(ins, st, mem, out, kx),
        Node::TidalPoly => tidal_poly::render(ins, st, mem, out, kx),
        Node::PeakFunction => peak_function::render(ins, st, mem, out, kx),
        Node::StageSegment => stage_segment::render(ins, st, mem, out, kx),
        Node::StageChain => stage_chain::render(ins, st, mem, out, kx),
        Node::FrameLfo => frame_lfo::render(ins, st, mem, out, kx),
        Node::FrameKeyframe { .. } => out.fill(0.0),
        Node::StageLinked { .. } => out.fill(0.0),
        Node::PeakPulse => peak_pulse::render(ins, st, mem, out, kx),
        Node::NumberStation => number_station::render(ins, st, mem, out, kx),
        Node::SpectrumPair => spectrum_pair::render(ins, st, mem, out, kx),
        Node::ClockNoisePair => clock_noise_pair::render(ins, st, out, kx),
        Node::DualKick => dual_kick::render(ins, st, mem, out, kx),
        Node::SnarePair => snare_pair::render(ins, st, mem, out, kx),
        Node::HatPair => hat_pair::render(ins, st, mem, out, kx),
        Node::SwarmPair => swarm_pair::render(ins, st, mem, out, kx),
        Node::ParticlePair => particle_pair::render(ins, st, mem, out, kx),
        Node::ModalPair => modal_pair::render(ins, st, mem, out, kx),
        Node::StringPair => string_pair::render(ins, st, mem, out, kx),
        Node::ChipPair => chip_pair::render(ins, st, mem, out, kx),
        Node::AnalogPair => analog_pair::render(ins, st, mem, out, kx),
        Node::GrainPair => grain_pair::render(ins, st, mem, out, kx),
        Node::ShapePair => shape_pair::render(ins, st, mem, out, kx),
        Node::VactrolGate => vactrol_gate::render_gate(ins, st, mem, out, kx),
        Node::DecayMod => vactrol_gate::render_decay_mod(ins, st, mem, out, kx),
        Node::StringMachinePair => string_machine_pair::render(ins, st, mem, out, kx),
        Node::TerrainPair => terrain_pair::render(ins, st, mem, out, kx),
        Node::TableTerrainPair => table_terrain_pair::render(ins, st, mem, out, kx),
        Node::ChordPair => chord_pair::render(ins, st, mem, out, kx),
        Node::BraidsFive => braids_five::render(ins, st, mem, out, kx),
        Node::BraidsSubSync => braids_subsync::render(ins, st, mem, out, kx),
        Node::BraidsTriple => braids_triple::render(ins, st, mem, out, kx),
        Node::BraidsDigital => braids_digital::render(ins, st, mem, out, kx),
        Node::BraidsFilter => braids_filter::render(ins, st, mem, out, kx),
        Node::BraidsFormant => braids_formant::render(ins, st, mem, out, kx),
        Node::BraidsFm => braids_fm::render(ins, st, mem, out, kx),
        Node::BraidsPhysical => braids_physical::render(ins, st, mem, out, kx),
        Node::BraidsStruck => braids_struck::render(ins, st, mem, out, kx),
        Node::BraidsPercussion => braids_percussion::render(ins, st, mem, out, kx),
        Node::BraidsWaveBank => braids_wave_bank::render(ins, st, mem, out, kx),
        Node::BraidsWaveLine => braids_wave_line::render(ins, st, mem, out, kx),
        Node::BraidsNoise => braids_noise::render(ins, st, mem, out, kx),
        Node::BraidsCloud => braids_cloud::render(ins, st, mem, out, kx),
        Node::FeedbackDrum => fusion_drum::feedback(ins, st, mem, out, kx),
        Node::NoiseDrum => fusion_drum::noise(ins, st, out, kx),
        Node::SineDrum => fusion_drum::sine(ins, st, out, kx),
        Node::PhaseDistortion => fm::phase_distortion(ins, st, out, kx),
        Node::Additive { partials_max } => additive::render(partials_max, ins, st, mem, out, kx),
        Node::Wavetable(t) => wavetable::render(t, ins, st, out, kx),
        Node::Granular(src) => crate::dsp::granular::ugen_process(src, ins, st, mem, out, kx),
        Node::Effect { .. } => out.fill(0.0),
    }
}
