//! Editor metadata for the six dedicated bass templates.

pub(super) const ANALOG_BASS: &[&str] = &[
    "freq",
    "wave",
    "cutoff",
    "res",
    "env-mod",
    "env-decay",
    "accent",
    "sub-level",
    "drive",
    "gate-length",
    "amp-attack",
    "amp-decay",
    "sustain",
    "release",
    "slide-from",
    "slide-time",
    "amp",
];

pub(super) const ACID_BASS: &[&str] = &[
    "freq",
    "wave",
    "cutoff",
    "res",
    "env-mod",
    "env-decay",
    "accent",
    "slide-from",
    "slide-time",
    "drive",
    "gate-length",
    "release",
    "amp",
];

pub(super) const FM_BASS: &[&str] = &[
    "freq",
    "ratio",
    "index",
    "fm-feedback",
    "fold",
    "bit-depth",
    "cutoff",
    "res",
    "env-mod",
    "env-decay",
    "accent",
    "drive",
    "gate-length",
    "amp-decay",
    "sustain",
    "release",
    "slide-from",
    "slide-time",
    "amp",
];

pub(super) const WOBBLE_BASS: &[&str] = &[
    "freq",
    "wave",
    "detune",
    "sub-level",
    "cutoff",
    "res",
    "drive",
    "lfo-wave",
    "lfo-rate",
    "lfo-depth",
    "lfo-offset",
    "lfo-retrigger",
    "lfo-sync",
    "gate-length",
    "release",
    "slide-from",
    "slide-time",
    "amp",
];

pub(super) const SUB_BASS: &[&str] = &[
    "freq",
    "wave",
    "cutoff",
    "res",
    "drive",
    "click-level",
    "gate-length",
    "amp-attack",
    "release",
    "slide-from",
    "slide-time",
    "amp",
];

pub(super) const REESE_BASS: &[&str] = &[
    "freq",
    "wave",
    "detune",
    "sub-level",
    "cutoff",
    "res",
    "env-mod",
    "env-decay",
    "drive",
    "gate-length",
    "amp-attack",
    "release",
    "slide-from",
    "slide-time",
    "amp",
];

/// Bass header defaults that differ from the row or kernel-port defaults.
pub const DEFAULT_OVERRIDES: &[(&str, &str, &str)] = &[
    ("analog-bass", "cutoff", "420"),
    ("analog-bass", "res", "0.35"),
    ("analog-bass", "env-mod", "2.5"),
    ("analog-bass", "env-decay", "0.18"),
    ("analog-bass", "sub-level", "0.35"),
    ("analog-bass", "drive", "0.25"),
    ("analog-bass", "gate-length", "0.9"),
    ("analog-bass", "amp-decay", "0.4"),
    ("analog-bass", "sustain", "0.85"),
    ("analog-bass", "release", "0.04"),
    ("analog-bass", "amp-attack", "0.002"),
    ("acid-bass", "cutoff", "320"),
    ("acid-bass", "res", "0.72"),
    ("acid-bass", "env-mod", "3.2"),
    ("acid-bass", "env-decay", "0.22"),
    ("acid-bass", "slide-time", "0.06"),
    ("acid-bass", "drive", "0.3"),
    ("acid-bass", "gate-length", "0.55"),
    ("acid-bass", "release", "0.02"),
    ("fm-bass", "index", "2.5"),
    ("fm-bass", "fm-feedback", "0.35"),
    ("fm-bass", "cutoff", "2400"),
    ("fm-bass", "res", "0.1"),
    ("fm-bass", "env-mod", "1"),
    ("fm-bass", "env-decay", "0.15"),
    ("fm-bass", "drive", "0.1"),
    ("fm-bass", "gate-length", "0.8"),
    ("fm-bass", "amp-decay", "0.25"),
    ("fm-bass", "sustain", "0.45"),
    ("fm-bass", "release", "0.05"),
    ("fm-bass", "slide-time", "0.05"),
    ("wobble-bass", "detune", "0.12"),
    ("wobble-bass", "sub-level", "0.4"),
    ("wobble-bass", "cutoff", "180"),
    ("wobble-bass", "res", "0.45"),
    ("wobble-bass", "drive", "0.35"),
    ("wobble-bass", "lfo-depth", "0.8"),
    ("wobble-bass", "lfo-sync", "true"),
    ("wobble-bass", "gate-length", "4"),
    ("wobble-bass", "release", "0.08"),
    ("wobble-bass", "slide-time", "0.08"),
    ("sub-bass", "wave", "sine"),
    ("sub-bass", "cutoff", "300"),
    ("sub-bass", "res", "0"),
    ("sub-bass", "drive", "0.15"),
    ("sub-bass", "click-level", "0.2"),
    ("sub-bass", "gate-length", "1.5"),
    ("sub-bass", "amp-attack", "0.003"),
    ("sub-bass", "release", "0.06"),
    ("sub-bass", "slide-time", "0.05"),
    ("reese-bass", "detune", "0.18"),
    ("reese-bass", "sub-level", "0.3"),
    ("reese-bass", "cutoff", "650"),
    ("reese-bass", "res", "0.2"),
    ("reese-bass", "env-mod", "0.8"),
    ("reese-bass", "env-decay", "0.6"),
    ("reese-bass", "drive", "0.3"),
    ("reese-bass", "gate-length", "3.5"),
    ("reese-bass", "amp-attack", "0.01"),
    ("reese-bass", "release", "0.12"),
    ("reese-bass", "slide-time", "0.1"),
];
