//! Editor parameter names for the six FM1 voice templates.

pub(super) const KALIMBA: &[&str] = &[
    "freq",
    "kalimba-beat",
    "kalimba-hardness",
    "kalimba-decay",
    "kalimba-damping",
    "kalimba-body",
    "kalimba-buzz",
    "amp",
];
pub(super) const TONEWHEEL_ORGAN: &[&str] = &[
    "freq",
    "drawbar1",
    "drawbar2",
    "drawbar3",
    "drawbar4",
    "drawbar5",
    "drawbar6",
    "drawbar7",
    "drawbar8",
    "drawbar9",
    "organ-click",
    "organ-perc",
    "organ-perc-slow",
    "organ-perc-soft",
    "organ-perc-trigger",
    "organ-vibrato",
    "gate-length",
    "amp",
];
pub(super) const HURDY_GURDY: &[&str] = &[
    "freq",
    "gurdy-wheel",
    "gurdy-pressure",
    "gurdy-melody",
    "gurdy-bourdon",
    "gurdy-fifth",
    "gurdy-trompette",
    "gurdy-drone-key",
    "gurdy-buzz",
    "gurdy-buzz-threshold",
    "gurdy-strokes",
    "gurdy-stroke-depth",
    "gate-length",
    "amp",
];
pub(super) const VOSIM: &[&str] = &[
    "freq",
    "vosim-formant",
    "vosim-pulses",
    "vosim-decay",
    "attack",
    "decay",
    "sustain",
    "release",
    "amp",
];
pub(super) const GENDYN: &[&str] = &[
    "freq",
    "gendyn-points",
    "gendyn-amp-step",
    "gendyn-dur-step",
    "gendyn-dist",
    "gendyn-spread",
    "attack",
    "decay",
    "sustain",
    "release",
    "amp",
];
pub(super) const SCANNED: &[&str] = &[
    "freq",
    "scan-stiffness",
    "scan-damping",
    "scan-centering",
    "scan-hammer",
    "scan-position",
    "scan-update",
    "attack",
    "decay",
    "sustain",
    "release",
    "amp",
];
