//! Source Warps vocoder filter coefficients only: 20 seven-scalar rows.
//!
//! Copyright 2014 Emilie Gillet. Author: Emilie Gillet.
//! Permission is hereby granted, free of charge, to any person obtaining a
//! copy of this software and associated documentation files (the "Software"),
//! to deal in the Software without restriction, including without limitation
//! the rights to use, copy, modify, merge, publish, distribute, sublicense,
//! and/or sell copies of the Software, and to permit persons to whom the
//! Software is furnished to do so, subject to the following conditions:
//! The above copyright notice and this permission notice shall be included
//! in all copies or substantial portions of the Software.
//! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
//! OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//! MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
//! IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
//! DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
//! OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
//! USE OR OTHER DEALINGS IN THE SOFTWARE.
//!
//! Individually extracted `fb_*` rows from MIT `warps/resources.cc` at
//! eurorack 08460a69, generated by MIT `warps/resources/filter_bank.py`.
//! No other aggregate resource data or oscillator wave samples are included.

#[allow(clippy::excessive_precision)]
pub(super) const BANDS: [[f32; 7]; 20] = [
    // fb__87_8000
    [
        1.200000000e+01,
        1.100000000e+02,
        1.000000000e+00,
        -7.027765790e-02,
        2.374233182e-02,
        -4.036276502e-02,
        5.641820638e-02,
    ],
    // fb_110_8000
    [
        1.200000000e+01,
        3.060000000e+02,
        2.500000000e-01,
        -9.339148150e-02,
        1.518494012e-02,
        -7.931045024e-02,
        1.290681251e-02,
    ],
    // fb_139_8000
    [
        1.200000000e+01,
        2.430000000e+02,
        2.500000000e-01,
        -1.175253889e-01,
        1.909187455e-02,
        -9.982608285e-02,
        1.623625964e-02,
    ],
    // fb_175_8000
    [
        1.200000000e+01,
        1.920000000e+02,
        2.500000000e-01,
        -1.478403116e-01,
        2.399019825e-02,
        -1.256102632e-01,
        2.041717073e-02,
    ],
    // fb_220_8000
    [
        1.200000000e+01,
        1.530000000e+02,
        2.500000000e-01,
        -1.858796047e-01,
        3.012281471e-02,
        -1.579890264e-01,
        2.566359509e-02,
    ],
    // fb_277_8000
    [
        1.200000000e+01,
        1.210000000e+02,
        2.500000000e-01,
        -2.335415850e-01,
        3.778648442e-02,
        -1.986017761e-01,
        3.224184764e-02,
    ],
    // fb_349_8000
    [
        1.200000000e+01,
        9.600000000e+01,
        2.500000000e-01,
        -2.931359041e-01,
        4.733980069e-02,
        -2.494585699e-01,
        4.048298668e-02,
    ],
    // fb_440_8000
    [
        1.200000000e+01,
        7.600000000e+01,
        2.500000000e-01,
        -3.674252077e-01,
        5.920914546e-02,
        -3.129923847e-01,
        5.079873862e-02,
    ],
    // fb_554_8000
    [
        1.200000000e+01,
        6.000000000e+01,
        2.500000000e-01,
        -4.596234805e-01,
        7.388912125e-02,
        -3.920877866e-01,
        6.370275117e-02,
    ],
    // fb_698_8000
    [
        1.200000000e+01,
        4.800000000e+01,
        2.500000000e-01,
        -5.732942351e-01,
        9.193058505e-02,
        -4.900471292e-01,
        7.984109811e-02,
    ],
    // fb_880_8000
    [
        1.200000000e+01,
        3.800000000e+01,
        2.500000000e-01,
        -7.120398134e-01,
        1.139025399e-01,
        -6.104158833e-01,
        1.000408086e-01,
    ],
    // fb_1109_8000
    [
        1.200000000e+01,
        3.000000000e+01,
        2.500000000e-01,
        -8.787817044e-01,
        1.402986139e-01,
        -7.565125704e-01,
        1.253975556e-01,
    ],
    // fb_1397_8000
    [
        1.200000000e+01,
        2.400000000e+01,
        2.500000000e-01,
        -9.303628940e-01,
        1.574589048e-01,
        -1.074283292e+00,
        1.713175349e-01,
    ],
    // fb_1760_32000
    [
        3.000000000e+00,
        7.600000000e+01,
        2.500000000e-01,
        -3.674252077e-01,
        5.920914546e-02,
        -3.129923847e-01,
        5.079873862e-02,
    ],
    // fb_2217_32000
    [
        3.000000000e+00,
        6.000000000e+01,
        2.500000000e-01,
        -4.596234805e-01,
        7.388912125e-02,
        -3.920877866e-01,
        6.370275117e-02,
    ],
    // fb_2794_32000
    [
        3.000000000e+00,
        4.800000000e+01,
        2.500000000e-01,
        -5.732942351e-01,
        9.193058505e-02,
        -4.900471292e-01,
        7.984109811e-02,
    ],
    // fb_3520_32000
    [
        3.000000000e+00,
        3.800000000e+01,
        2.500000000e-01,
        -7.120398134e-01,
        1.139025399e-01,
        -6.104158833e-01,
        1.000408086e-01,
    ],
    // fb_4435_32000
    [
        3.000000000e+00,
        3.000000000e+01,
        2.500000000e-01,
        -8.787817044e-01,
        1.402986139e-01,
        -7.565125704e-01,
        1.253975556e-01,
    ],
    // fb_5588_32000
    [
        3.000000000e+00,
        2.400000000e+01,
        2.500000000e-01,
        -9.303628940e-01,
        1.574589048e-01,
        -1.074283292e+00,
        1.713175349e-01,
    ],
    // fb_7040_96000
    [
        1.000000000e+00,
        6.000000000e+00,
        3.080000000e+00,
        -4.088135601e-01,
        1.514311173e-01,
        -5.414722362e-01,
        6.413463290e-01,
    ],
];
