#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const args=process.argv.slice(2);const opt=(k,d)=>{const i=args.indexOf(k);return i<0?d:args[i+1];};
const app=opt('--app','');const device=opt('--device','iPad Pro 11-inch (M5)');const out=path.resolve(opt('--out',path.join(path.dirname(fileURLToPath(import.meta.url)),'../../../design-docs/specs/evidence/canvas-cutover/run-001/ios-sim.json')));const runDir=path.dirname(out);fs.mkdirSync(runDir,{recursive:true});
const run=(cmd,argv,options={})=>spawnSync(cmd,argv,{encoding:'utf8',timeout:180000,...options});const result={device,app,host:os.hostname(),commands:[],blocked:false};
function save(){fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');}
if(!app||!fs.existsSync(app)){result.blocked=true;result.reason=`iOS simulator .app unavailable: --app path '${app||'<not supplied>'}' does not exist; CANVAS-SHELL must provide a built app. Build command: tmp/canvas/tools/cargo-tauri ios build --target aarch64-sim.`;result.exitCode=2;save();console.log(JSON.stringify(result));process.exit(2);}
let devices=run('xcrun',['simctl','list','devices','available','--json']);result.commands.push({command:'xcrun simctl list devices available --json',exitStatus:devices.status,output:devices.stdout,stderr:devices.stderr});
let udid='',deviceState='';try{const obj=JSON.parse(devices.stdout);for(const group of Object.values(obj.devices)) {const hit=group.find(d=>d.name===device);if(hit){udid=hit.udid;deviceState=hit.state;break;}}}catch{}
if(!udid){result.blocked=true;result.reason=`Named iPad simulator '${device}' is not installed/available.`;result.exitCode=2;save();console.log(JSON.stringify(result));process.exit(2);}
let boot={status:0,stdout:'already booted',stderr:''};if(deviceState!=='Booted'){boot=run('xcrun',['simctl','boot',udid]);}result.commands.push({command:deviceState==='Booted'?`xcrun simctl bootstatus ${udid} -b (already booted)`:`xcrun simctl boot ${udid}`,exitStatus:boot.status,output:boot.stdout,stderr:boot.stderr});if(boot.status!==0){result.blocked=true;result.reason=`Simulator boot failed: ${boot.stderr}`;result.exitCode=2;save();console.log(JSON.stringify(result));process.exit(2);}
const install=run('xcrun',['simctl','install',udid,app]);result.commands.push({command:`xcrun simctl install ${udid} ${app}`,exitStatus:install.status,output:install.stdout,stderr:install.stderr});
let bundle='';try{bundle=JSON.parse(fs.readFileSync(path.join(app,'Info.plist.json'),'utf8')).CFBundleIdentifier;}catch{}
if(!bundle){const p=run('/usr/libexec/PlistBuddy',['-c','Print :CFBundleIdentifier',path.join(app,'Info.plist')]);bundle=p.stdout.trim();}
if(install.status!==0||!bundle){result.blocked=true;result.reason=`Simulator install failed or app bundle identifier was unavailable: ${install.stderr||'missing CFBundleIdentifier'}`;result.exitCode=2;save();console.log(JSON.stringify(result));process.exit(2);}
const launch=run('xcrun',['simctl','launch',udid,bundle],{env:{...process.env,SIMCTL_CHILD_VACTR_SELF_CHECK:'1'}});result.commands.push({command:`SIMCTL_CHILD_VACTR_SELF_CHECK=1 xcrun simctl launch ${udid} ${bundle}`,exitStatus:launch.status,output:launch.stdout,stderr:launch.stderr});
let logs={status:0,stdout:'',stderr:''};for(let attempt=0;attempt<8;attempt++){logs=run('xcrun',['simctl','spawn',udid,'log','show','--last','2m','--style','compact','--predicate','eventMessage CONTAINS \"VACTR_SELF_CHECK {\"']);if(logs.stdout.includes('VACTR_SELF_CHECK {'))break;run('sleep',['1']);}result.commands.push({command:`xcrun simctl spawn ${udid} log show --last 2m --style compact --predicate 'eventMessage CONTAINS \"VACTR_SELF_CHECK {\"'`,exitStatus:logs.status,output:logs.stdout,stderr:logs.stderr});
result.selfCheckLine=(logs.stdout+'\n'+launch.stdout).split(/\r?\n/).find((line)=>/VACTR_SELF_CHECK \{/.test(line))??null;
try{const match=result.selfCheckLine?.match(/VACTR_SELF_CHECK\s+(\{.*\})/);result.selfCheck=match?JSON.parse(match[1]):null;}catch{result.selfCheck=null;}
result.silent=result.selfCheck?.playingEvents===0;
const screenshot=path.resolve('tmp/canvas-cutover/evidence/ios-sim.png');const shot=run('xcrun',['simctl','io',udid,'screenshot',screenshot]);result.commands.push({command:`xcrun simctl io ${udid} screenshot ${screenshot}`,exitStatus:shot.status,output:shot.stdout,stderr:shot.stderr});result.screenshot=screenshot;
result.pass=boot.status===0&&install.status===0&&launch.status===0&&logs.status===0&&shot.status===0&&Boolean(result.selfCheckLine)&&result.silent;result.exitCode=result.pass?0:1;if(!result.pass)result.reason=result.selfCheckLine?'Simulator self-check reports playingEvents other than zero or a simulator command failed.':'Simulator app launched or screenshot was captured, but VACTR_SELF_CHECK evidence is absent or a command failed.';save();console.log(JSON.stringify(result));process.exit(result.exitCode);
